---
title: "2003-2024 data"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(tidyverse)
```

```{r}
df <- read_csv('../data/final_data.csv')

testing_df <- function(df,
                       date_col = "caldt",
                       fund_col = "crsp_fundno",
                       test_start_year = 2025,
                       test_end_year = 2025) {
  
  df <- df %>%
    mutate(
      !!date_col := as.Date(.data[[date_col]])
    ) %>%
    arrange(.data[[date_col]])
  
  
  for (yr in test_start_year:test_end_year) {
    
    train_cutoff <- as.Date(paste0(yr, "-12-31"))
    
    train_df <- df %>%
      filter(.data[[date_col]] <= train_cutoff)
    
    # Standardisation
    train_df_std <- train_df %>%
      mutate(year_tmp = lubridate::year(.data[[date_col]])) %>%
      group_by(year_tmp) %>%
      mutate(across(
        .cols = where(is.numeric) & !any_of(c("year_tmp", fund_col, "alpha_ann")),
        .fns  = ~ {
          mu  <- mean(.x, na.rm = TRUE)
          sdv <- sd(.x, na.rm = TRUE)
          
          if (!is.na(sdv) && sdv > 0) {
            z <- (.x - mu) / sdv
          } else {
            z <- rep(0, length(.x))
          }
          
          z[is.na(z)] <- 0
          z
        }
      )) %>%
      ungroup() %>% 
      select(-year_tmp)
    
    # Save CSV
    file_name <- "df_for_shap_analysis.csv"
    write.csv(train_df_std, file_name, row.names = FALSE)
  }
    
   
} 

testing = testing_df(df)
```


