---
title: "NN De Miguel"
author: "Yun Tsing"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)      
library(tidyr)     
library(lubridate)
library(h2o)
```

```{r}
# Initialise h2o
tryCatch({
  h2o.init(nthreads = 1, max_mem_size = "4G")
}, error = function(e) {
  message("H2O is already running.")
})
```

```{r}
predict_alpha_nn_h2o <- function(df, target = "alpha_ann", layers = 3) {
  
  chosen_hidden <- switch(as.character(layers),
                         "1" = list(c(32)),
                         "2" = list(c(32, 16)),
                         "3" = list(c(32, 16, 8)),
                         stop("Invalid layer count. Use 1, 2, or 3."))
  
  df$caldt <- lubridate::as_date(df$caldt)
  features <- setdiff(names(df), c("crsp_fundno", "caldt", "alpha_ann"))
  
  all_years <- lubridate::year(df$caldt)
  pred_year <- max(all_years)
  
  # Data splitting
  train_full <- df[all_years < pred_year, ]
  test       <- df[all_years == pred_year, ]
  
  train_years_list <- sort(unique(lubridate::year(train_full$caldt)))
  cutoff           <- train_years_list[floor(length(train_years_list) * 0.7)]
  
  tune_train_df <- train_full[lubridate::year(train_full$caldt) <= cutoff, ]
  tune_val_df   <- train_full[lubridate::year(train_full$caldt) >  cutoff, ]
  
  train_h2o      <- h2o::as.h2o(tune_train_df)
  val_h2o        <- h2o::as.h2o(tune_val_df)
  test_h2o       <- h2o::as.h2o(test)
  full_train_h2o <- h2o::as.h2o(train_full) 
  
  # Grid search
  hyper_params <- list(
    hidden = chosen_hidden, 
    l1 = c(1e-4, 1e-3, 1e-2),
    l2 = c(1e-4, 1e-3, 1e-2),
    input_dropout_ratio = c(0, 0.1, 0.2), 
    hidden_dropout_ratios = list(rep(0.3, layers), rep(0.5, layers)) 
  )
  
  grid <- h2o::h2o.grid(
    algorithm = "deeplearning",
    grid_id = paste0("nn_grid_", pred_year, "_L", layers),
    x = features,
    y = target,
    training_frame = train_h2o,
    validation_frame = val_h2o,       
    seed = 4101,
    reproducible = TRUE,
    hyper_params = hyper_params,
    activation = "TanhWithDropout",  
    epochs = 50,          
    stopping_rounds = 10, 
    standardize = TRUE,
    adaptive_rate = TRUE,
    stopping_metric = "MSE"
  
  )
  
  # Identify best model
  grid_results <- h2o::h2o.getGrid(grid@grid_id, sort_by = "mse", decreasing = FALSE)
  best_model <- h2o::h2o.getModel(grid_results@model_ids[[1]])
  
  seeds <- c(4101, 4102, 4103, 4104, 4105)
  ensemble_preds <- matrix(0, nrow = nrow(test), ncol = length(seeds))
  
  for(i in 1:length(seeds)) {
    cat(sprintf("\nSeed %d of 5 for Year %d \n", i, pred_year))
    
    m_final <- h2o::h2o.deeplearning(
      x = features, y = target,
      training_frame = full_train_h2o,
      hidden = best_model@parameters$hidden, 
      l1 = best_model@parameters$l1,
      l2 = best_model@parameters$l2,
      input_dropout_ratio = best_model@parameters$input_dropout_ratio,
      hidden_dropout_ratios = best_model@parameters$hidden_dropout_ratios, 
      epochs = 50,
      activation = "TanhWithDropout",
      standardize = TRUE,
      adaptive_rate = TRUE,
      seed = seeds[i],
      reproducible = TRUE
    )
    
    p <- h2o::h2o.predict(m_final, test_h2o)
    ensemble_preds[, i] <- as.numeric(as.vector(p$predict))
    h2o::h2o.rm(m_final) 
  }
  
  res <- data.frame(
    evaluation_year = pred_year,
    crsp_fundno = test$crsp_fundno,
    predicted_alpha = rowMeans(ensemble_preds) 
  )
  
  h2o::h2o.rm(train_h2o); h2o::h2o.rm(val_h2o); h2o::h2o.rm(test_h2o); h2o::h2o.rm(full_train_h2o)
  
  return(res)
}
```